### ISSUE TITLE
Can't edit existing alarms using Add New Alarm service

### ISSUE THREAD

**Issue by The-Croz** [pa-innovation/ha-doppler#1]
## Version of the custom_component

latest
## Configuration
This won't work as the way the service call currently works it requires color, name, volume, status, and sound. It would be great to just use this to update the time for an existing alarm
```yaml
service: sandman_doppler.add_alarm
data:
  time: "06:00:00"
  id: 0
target:
  entity_id: switch.alarm_clock_alarm_0_doppler_system_alarm
```
And even if I include all the required info to send a service call, it just ignores the id that is input and creates a new alarm on the next open id number:
```yaml
service: sandman_doppler.add_alarm
data:
  time: "06:30:00"
  color:
    - 255
    - 0
    - 0
  name: Doppler System
  volume: 100
  status: set
  sound: Harp.mp3
  id: 0
target:
  entity_id: switch.alarm_clock_alarm_0_doppler_system_alarm
```

## Describe the bug
The service to add new alarms will not edit existing alarms as it should based on the service description "Sets an Alarm on the Doppler. If the ID is unused, the alarm will be created as new. If the ID is in use, the existing alarm will be replaced." It will create new alarms on the next open id number no matter what is put in the service call.

Also, it would be great to only require the entity and id number for the service from this integration. This way, any parameter(s) of the alarm could be adjusted without having to reset all of them.

## Debug log

N/A
